from datetime import datetime
from typing import List, Dict, Any
import warnings

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, Border, Side
from openpyxl.utils import get_column_letter, range_boundaries
from openpyxl.worksheet.page import PageMargins

from sn_rating.config import load_config
from sn_rating.run_from_excel import run_from_excel_with_bands, _infer_time_labels
from sn_rating.helpers import get_rating_band, input_path, output_path



def generate_corporate_rating_report(result) -> str:
    """Create a formatted Excel report (main + log sheets) from RatingOutputs."""
    
    res = result  # Alias for brevity
    cfg = load_config()
    score_to_rating = cfg["SCORE_TO_RATING"]    

    # ------------------------------------------------------------------
    # Load input sheets for display (only for showing original ratios/factors)
    # ------------------------------------------------------------------
    rating_input_file = input_path("sn_rating_input.xlsx")  # Input workbook path

    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
        with pd.ExcelFile(rating_input_file) as xls:
            df_fin = pd.read_excel(xls, sheet_name="fin_ratios", index_col=0)
            df_qual = pd.read_excel(xls, sheet_name="qual_factors", index_col=0)
            df_meta = pd.read_excel(xls, sheet_name="metadata")
            df_peers = pd.read_excel(xls, sheet_name="peers_t0")

    # Drop unnamed helper columns
    df_fin = df_fin.loc[:, ~df_fin.columns.str.contains("^Unnamed")]
    df_qual = df_qual.loc[:, ~df_qual.columns.str.contains("^Unnamed")]

    YEAR_T0, YEAR_T1, YEAR_T2 = _infer_time_labels(df_fin)  # Infer T0/T1/T2 labels

    meta = dict(zip(df_meta["field"], df_meta["value"]))  # metadata → dict

    raw_name = str(meta.get("name", "")).strip()
    issuer_name = raw_name.title()
    sovereign_rating: Optional[str] = (meta.get("sovereign_rating") or "").strip() or None
    sovereign_outlook: Optional[str] = (meta.get("sovereign_outlook") or "").strip() or None

    enable_hardstops = res.flags.get("enable_hardstops", False)
    enable_sovereign_cap = res.flags.get("enable_sovereign_cap", False)
    enable_peer_positioning = res.flags.get("enable_peer_positioning", False)

    peer_avg_fin: Dict[str, float] = {}  # Peer averages for ratios
    peer_score = res.peer_score          # Already computed by model

    if enable_peer_positioning and not df_peers.empty:
        df_peers_indexed = df_peers.set_index(df_peers.columns[0])  # First col as index
        for ratio in df_fin.index:
            if ratio in df_peers_indexed.index:
                peer_avg_fin[ratio] = df_peers_indexed.loc[ratio].mean()

    # ------------------------------------------------------------------
    # Set up main workbook and sheet
    # ------------------------------------------------------------------
    wb = Workbook()
    ws = wb.active
    ws.title = "Rating Report"

    bold = Font(bold=True)
    title_font = Font(size=14, bold=True)

    # Column widths for main report
    widths = [23, 13, 13, 23, 13, 13]
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w

    # Report title row
    ws.merge_cells("A1:F1")
    ws["A1"] = "CORPORATE CREDIT RATING REPORT"
    ws["A1"].font = title_font
    ws["A1"].alignment = Alignment(horizontal="center")

    report_date = datetime.today().strftime("%Y-%m-%d")
    run_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    internal_id = f"RR-{datetime.today().strftime('%Y%m%d')}"  # Simple daily ref

    header = [
        ("Issuer Name", issuer_name, "Internal Ref ID", internal_id),
        ("Report Date", report_date, "Run Timestamp", run_timestamp),
        ("Final Rating", res.final_rating, "Generated By", "SN Corporate Rating Model"),
        ("Outlook", res.final_outlook, "Model Version", "V1.0"),
    ]

    row = 3
    for left_label, left_val, right_label, right_val in header:
        ws[f"A{row}"] = left_label
        ws[f"A{row}"].font = bold
        ws[f"B{row}"] = left_val
        ws[f"D{row}"] = right_label
        ws[f"D{row}"].font = bold
        ws[f"E{row}"] = right_val
        row += 1

    row += 1  # blank row after header block

    # Section headers for ratios/factors
    ws[f"A{row}"] = "Quantitative ratios"
    ws[f"A{row}"].font = bold
    ws[f"B{row}"] = YEAR_T0
    ws[f"C{row}"] = YEAR_T1

    ws[f"D{row}"] = "Qualitative factors"
    ws[f"D{row}"].font = bold
    ws[f"E{row}"] = YEAR_T0
    ws[f"F{row}"] = YEAR_T1

    # Bold + center A..F (so FY24 on the qual side is included)
    for col in range(1, 7):
        cell = ws.cell(row=row, column=col)
        cell.font = bold
        cell.alignment = Alignment(horizontal="center")

    row += 1  # move to first data row

    # ------------------------------------------------------------------
    # Build ordered lists from logs (to choose which rows to show)
    # ------------------------------------------------------------------
    ratio_rows: List[tuple] = []
    for r in res.ratio_log:
        name = r.get("Name")
        if not name:
            continue
        if name not in df_fin.index:
            continue
        ratio_rows.append((name, r.get("Value")))
    fin_index = [name for name, _ in ratio_rows]

    qual_rows: List[str] = []
    for r in res.qual_log:
        name = r.get("Name")
        if not name:
            continue
        qual_rows.append(name)

    if qual_rows:
        qual_index = qual_rows
    else:
        qual_index = list(df_qual.index)

    table_start_row = row
    TABLE_ROWS = max(20, len(fin_index), len(qual_index))

    for i in range(TABLE_ROWS):
        if i < len(fin_index):
            ratio = fin_index[i]
            ws[f"A{row}"] = ratio
            ws[f"B{row}"] = df_fin.loc[ratio].get(YEAR_T0)
            ws[f"C{row}"] = df_fin.loc[ratio].get(YEAR_T1)
            for col in ("B", "C"):
                cell = ws[f"{col}{row}"]
                if isinstance(cell.value, (int, float)):
                    cell.number_format = "0.00"
                    cell.alignment = Alignment(horizontal="right")

        if i < len(qual_index):
            factor = qual_index[i]
            ws[f"D{row}"] = factor
            ws[f"E{row}"] = df_qual.loc[factor].get(YEAR_T0)
            ws[f"F{row}"] = df_qual.loc[factor].get(YEAR_T1)
            for col in ("E", "F"):
                cell = ws[f"{col}{row}"]
                if isinstance(cell.value, (int, float)):
                    cell.number_format = "0.00"
                    cell.alignment = Alignment(horizontal="right")

        row += 1

    table_end_row = row - 1

    row += 1  # blank row after ratios/factors table
    score_start = row

    # ------------------------------------------------------------------
    # Score summary block (right-hand side)
    # ------------------------------------------------------------------
    score_block = [
        ("Quantitative Score", res.quantitative_score),
        ("Qualitative Score", res.qualitative_score),
        ("Combined Score", res.combined_score),
        ("Base Rating/Outlook", f"{res.base_rating}/{res.base_outlook}"),
        ("Hard Stop Rating/Outlook", f"{res.hardstop_rating}/{res.hardstop_outlook}"),
        ("Final Rating/Outlook", f"{res.final_rating}/{res.final_outlook}"),
    ]

    for label, value in score_block:
        ws[f"D{row}"] = label
        ws[f"D{row}"].font = bold
        ws[f"F{row}"] = value
        row += 1

    score_block_end_row = row - 1

    # ------------------------------------------------------------------
    # Flags block on left side
    # ------------------------------------------------------------------
    flags = [
        ("Peer positioning enabled", enable_peer_positioning),
        ("Hardstop enabled",         enable_hardstops),
        ("Sovereign cap enabled",    enable_sovereign_cap),
        ("Hardstop triggered",       res.hardstop_triggered),
        ("Distress_notches",         res.distress_notches),
        ("Sovereign Rating/Outlook", f"{sovereign_rating}/{sovereign_outlook}"),
    ]

    for i, (label, value) in enumerate(flags):
        ws[f"A{score_start+i}"] = label
        ws[f"A{score_start+i}"].font = bold
        ws[f"C{score_start+i}"] = value

    flags_end_row = score_start + len(flags) - 1

    # ------------------------------------------------------------------
    # Rating rationale block
    # ------------------------------------------------------------------
    # One blank row between flags and RATING RATIONALE
    row = flags_end_row + 1  # empty spacer row
    row += 1                 # RATING RATIONALE title row
    rating_title_row = row

    ws[f"A{rating_title_row}"] = "RATING RATIONALE"
    ws[f"A{rating_title_row}"].font = bold

    row += 1                 # first line of text
    rationale_top = row
    rationale_height = 10
    rationale_bottom = rationale_top + rationale_height - 1

    ws.merge_cells(start_row=rationale_top, start_column=1,
                   end_row=rationale_bottom, end_column=6)
    ws[f"A{rationale_top}"] = res.rating_explanation
    ws[f"A{rationale_top}"].alignment = Alignment(wrap_text=True, vertical="top")

    # ------------------------------------------------------------------
    # Page setup (A4, fit to one page)
    # ------------------------------------------------------------------
    ws.page_setup.orientation = ws.ORIENTATION_PORTRAIT
    ws.page_setup.paperSize = ws.PAPERSIZE_A4
    ws.page_margins = PageMargins(
        left=0.3,
        right=0.3,
        top=0.5,
        bottom=0.5,
        header=0.2,
        footer=0.2,
    )
    ws.sheet_properties.pageSetUpPr.fitToPage = True
    ws.page_setup.fitToWidth = 1
    ws.page_setup.fitToHeight = 1
    last_row = rationale_bottom
    ws.print_area = f"A1:F{last_row}"

    # Align flags and score numbers to the right
    for r in range(score_start, score_start + len(flags)):
        ws[f"C{r}"].alignment = Alignment(horizontal="right")

    for r in range(score_start, score_start + len(score_block)):
        c = ws[f"F{r}"]
        c.alignment = Alignment(horizontal="right")
        if isinstance(c.value, (int, float)):
            c.number_format = "0.00"

    # ------------------------------------------------------------------
    # Borders
    # ------------------------------------------------------------------
    thick = Side(style="thick")

    def apply_outer_thick_border(ws_, rng: str) -> None:
        """Draw a thick border around a rectangular cell range."""
        min_col, min_row, max_col, max_row = range_boundaries(rng)
        for row_cells in ws_.iter_rows(
            min_row=min_row,
            max_row=max_row,
            min_col=min_col,
            max_col=max_col,
        ):
            for cell in row_cells:
                b = cell.border
                top = b.top
                bottom = b.bottom
                left = b.left
                right = b.right

                if cell.row == min_row:
                    top = thick
                if cell.row == max_row:
                    bottom = thick
                if cell.column == min_col:
                    left = thick
                if cell.column == max_col:
                    right = thick

                cell.border = Border(top=top, bottom=bottom, left=left, right=right)

    # Outer frame from title through rationale bottom (keep)
    table_frame_bottom = table_end_row + 1  # one row after the last ratio row
    score_frame_bottom = flags_end_row + 1  # one row after last flag row
    
    apply_outer_thick_border(ws, f"A1:F{rationale_bottom}")
    apply_outer_thick_border(ws, "A2:F7")
    apply_outer_thick_border(ws, f"A{table_start_row}:F{table_frame_bottom}")
    apply_outer_thick_border(ws, f"A{table_start_row}:C{table_frame_bottom}")
    apply_outer_thick_border(ws, f"A{score_start}:F{score_frame_bottom}")
    apply_outer_thick_border(ws, f"A{score_start}:C{score_frame_bottom}")

    # ------------------------------------------------------------------
    # Log sheet (ratio log + peer/distress summary)
    # ------------------------------------------------------------------
    log_ws = wb.create_sheet(title="ratio_log")

    log_rows: List[Dict[str, Any]] = []
    log_rows.extend(res.ratio_log)                         # Start with detailed ratio log

    # Derive peer counts from PeerFlag in ratio_log
    under_count = sum(1 for r in res.ratio_log if r.get("PeerFlag") == "under")
    over_count = sum(1 for r in res.ratio_log if r.get("PeerFlag") == "over")
    on_par_count = sum(1 for r in res.ratio_log if r.get("PeerFlag") == "on_par")
    total_count = under_count + over_count + on_par_count

    # Blank separator
    log_rows.append({"Name": "", "Value": "", "Score": "", "PeerFlag": None})
    
    peer_score = res.peer_score
    # Under / total share (simple peer underperformance share)
    if total_count > 0:
        under_share = under_count / total_count
    else:
        under_share = None

    for row_dict in log_rows:
        if row_dict.get("Name") == "peer_positioning":
            row_dict["Value"] = peer_score
            break

    # Summary rows based on flags/aggregates
    log_rows.append(
        {
            "Name": "peer_positioning",
            "Value": under_share,   
            "Score": res.peer_score,
            "PeerFlag": None,
        }
    )
    
    log_rows.append(
        {
            "Name": "Peer positioning enabled",
            "Value": res.flags.get("enable_peer_positioning", False),
            "Score": "",
            "PeerFlag": None,
        }
    )
    log_rows.append(
        {
            "Name": "peer_underperform_count",
            "Value": under_count,
            "Score": "",
            "PeerFlag": None,
        }
    )
    log_rows.append(
        {
            "Name": "peer_outperform_count",
            "Value": over_count,
            "Score": "",
            "PeerFlag": None,
        }
    )
    log_rows.append(
        {
            "Name": "peer_on_par_count",
            "Value": on_par_count,
            "Score": "",
            "PeerFlag": None,
        }
    )
    log_rows.append(
        {
            "Name": "peer_total_compared",
            "Value": total_count,
            "Score": "",
            "PeerFlag": None,
        }
    )

    log_rows.append(
        {
            "Name": "aggregate quantitative score",
            "Value": "",
            "Score": res.quantitative_score,
            "PeerFlag": None,
        }
    )
    log_rows.append(
        {
            "Name": "aggregate qualitative score",
            "Value": "",
            "Score": res.qualitative_score,
            "PeerFlag": None,
        }
    )

    log_rows.append(
        {
            "Name": "n_quant/weights",
            "Value": getattr(res, "n_quant", None),
            "Score": getattr(res, "wq", None),
            "PeerFlag": None,
        }
    )
    log_rows.append(
        {
            "Name": "n_qual/weights",
            "Value": getattr(res, "n_qual", None),
            "Score": getattr(res, "wl", None),
            "PeerFlag": None,
        }
    )

    log_rows.append(
        {
            "Name": "combined_score",
            "Value": res.combined_score,
            "Score": "",
            "PeerFlag": None,
        }
    )

    band_min, band_max = get_rating_band(res.base_rating, score_to_rating)
    band_range_str = f"{int(band_min)}-{int(band_max)}"
    log_rows.append(
        {
            "Name": "band_position",
            "Value": band_range_str,
            "Score": res.band_position,
            "PeerFlag": None,
        }
    )


    # Build DataFrame and preserve peer/distress columns
    log_df = pd.DataFrame(log_rows)

    # Ensure base columns exist
    for col in [
        "Name",
        "Value",
        "Score",
        "Weight",
        "PeerFlag",
        "PeerAvg",
        "PeerLowerBound",
        "PeerUpperBound",
        "DistressNotches",
    ]:
        if col not in log_df.columns:
            log_df[col] = None

    log_df = log_df[
        [
            "Name",
            "Value",
            "Score",
            "Weight",
            "PeerFlag",
            "PeerAvg",
            "PeerLowerBound",
            "PeerUpperBound",
            "DistressNotches",
        ]
    ]

    # Write header row
    bold = Font(bold=True)
    for j, col in enumerate(log_df.columns, start=1):
        log_ws.cell(row=1, column=j, value=col).font = bold

    # Write data rows with number formats and alignment
    for i, (_, row_series) in enumerate(log_df.iterrows(), start=2):
        name = row_series["Name"]

        log_ws.cell(row=i, column=1, value=name)

        v_cell = log_ws.cell(row=i, column=2, value=row_series["Value"])
        s_cell = log_ws.cell(row=i, column=3, value=row_series["Score"])
        w_cell = log_ws.cell(row=i, column=4, value=row_series["Weight"])       
        p_cell = log_ws.cell(row=i, column=5, value=row_series["PeerFlag"])
        avg_cell = log_ws.cell(row=i, column=6, value=row_series["PeerAvg"])
        lb_cell = log_ws.cell(row=i, column=7, value=row_series["PeerLowerBound"])
        ub_cell = log_ws.cell(row=i, column=8, value=row_series["PeerUpperBound"])
        dn_cell = log_ws.cell(row=i, column=9, value=row_series["DistressNotches"])

        # Number formatting
        if isinstance(row_series["Value"], (int, float)):
            if name in {
                "peer_underperform_count",
                "peer_outperform_count",
                "peer_on_par_count",
                "peer_total_compared",
                "n_quant/weights",
                "n_qual/weights",
                "distress_notches",
            }:
                v_cell.number_format = "0"
            else:
                v_cell.number_format = "0.00"

        if isinstance(row_series["Score"], (int, float)):
            s_cell.number_format = "0.00"
        if isinstance(row_series["Weight"], (int, float)):
            w_cell.number_format = "0.00"
        if isinstance(row_series["PeerAvg"], (int, float)):
            avg_cell.number_format = "0.00"
        if isinstance(row_series["PeerLowerBound"], (int, float)):
            lb_cell.number_format = "0.00"
        if isinstance(row_series["PeerUpperBound"], (int, float)):
            ub_cell.number_format = "0.00"
        if isinstance(row_series["DistressNotches"], (int, float)):
            dn_cell.number_format = "0"

        # Right-align numeric cells
        for cell in (v_cell, s_cell, w_cell, p_cell, avg_cell, lb_cell, ub_cell, dn_cell):
            cell.alignment = Alignment(horizontal="right")
       
    # Column widths for log sheet
    for col_letter, width in zip(
        ["A", "B", "C", "D", "E", "F", "G", "H","I"],
        [30, 20, 15, 12, 12, 15, 15, 15, 15],
    ):
        log_ws.column_dimensions[col_letter].width = width

    # ------------------------------------------------------------------
    # Optional: qualitative log sheet
    # ------------------------------------------------------------------
    if res.qual_log:          # will be False only if the list is empty
        qual_ws = wb.create_sheet(title="qual_log")
        qual_df = pd.DataFrame(res.qual_log)

        # Ensure standard columns
        for col in ["Name", "Value", "Score", "Weight", "Bucket"]:
            if col not in qual_df.columns:
                qual_df[col] = None
        qual_df = qual_df[["Name", "Value", "Score", "Weight", "Bucket"]]

        for j, col in enumerate(qual_df.columns, start=1):
            qual_ws.cell(row=1, column=j, value=col).font = bold

        for i, (_, row_series) in enumerate(qual_df.iterrows(), start=2):
            qual_ws.cell(row=i, column=1, value=row_series["Name"])
            v_cell = qual_ws.cell(row=i, column=2, value=row_series["Value"])
            s_cell = qual_ws.cell(row=i, column=3, value=row_series["Score"])
            w_cell = qual_ws.cell(row=i, column=4, value=row_series["Weight"])
            b_cell = qual_ws.cell(row=i, column=5, value=row_series["Bucket"])

            if isinstance(row_series["Value"], (int, float)):
                v_cell.number_format = "0"
            if isinstance(row_series["Score"], (int, float)):
                s_cell.number_format = "0.00"
            if isinstance(row_series["Weight"], (int, float)):
                w_cell.number_format = "0.00"

            for cell in (v_cell, s_cell, w_cell):
                cell.alignment = Alignment(horizontal="right")

        for col_letter, width in zip(["A", "B", "C", "D", "E"], [30, 15, 15, 15, 20]):
            qual_ws.column_dimensions[col_letter].width = width

    # ------------------------------------------------------------------
    # Save workbook to output folder
    # ------------------------------------------------------------------
    safe_name = issuer_name.replace(" ", "_")
    out_file = output_path(f"{safe_name}_Corporate_Credit_Rating_Report.xlsx")

    wb.save(out_file)
    return out_file